image: python:3

before_script:
  - pip install tox

stages:
  - lint
  - test

flake8:
  stage: lint
  script:
    - tox -e flake8

isort:
  stage: lint
  script:
    - tox -e isort

#Django 1.8

py34-dj18:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj18

py35-dj18:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj18

# Django 1.9
py34-dj19:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj19

py35-dj19:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj19

# Django 1.10

py34-dj110:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj110

py35-dj110:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj110

# Django 1.11

py34-dj111:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj111

py35-dj111:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj111

py36-dj111:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj111

# Django 2.0

py34-dj20:
  image: python:3.4
  stage: test
  script:
    - tox -e py34-dj20

py35-dj20:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj20

py36-dj20:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj20

py37-dj20:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj20

# Django 2.1

py35-dj21:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj21

py36-dj21:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj21

py37-dj21:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj21

# Django 2.2

py35-dj22:
  image: python:3.5
  stage: test
  script:
    - tox -e py35-dj22

py36-dj22:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj22

py37-dj22:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj22

py38-dj22:
  image: python:3.8
  stage: test
  script:
    - tox -e py38-dj22

# Django 3.0
py36-dj30:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-dj30

py37-dj30:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-dj30

py38-dj30:
  image: python:3.8
  stage: test
  script:
    - tox -e py38-dj30

# Django master
py36-djmaster:
  image: python:3.6
  stage: test
  script:
    - tox -e py36-djmaster

py37-djmaster:
  image: python:3.7
  stage: test
  script:
    - tox -e py37-djmaster

py38-djmaster:
  image: python:3.8
  stage: test
  script:
    - tox -e py38-djmaster
