name: Release

on:
  release:
    types: [published, prereleased]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3

      - name: Install dependencies
        run: python -m pip install --upgrade setuptools wheel

      - name: Build Python package
        run: python setup.py bdist_wheel sdist

      - name: Upload Python package
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist

      - name: Publish a Python distribution to test PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.pypi_test_token }}
